
version: 2

sources:
  - name: sourceinfos
    description: "a starter source table"
    tables:
      - name: testtable
        columns:
          - name: id
            data_tests:
              - unique
              - not_null


models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null

  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
